language: python
virtualenv:
  system_site_packages: true
env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="2.7" INSTALL_ATLAS="true"
      NUMPY_VERSION="1.8" SCIPY_VERSION="0.14"
      COVERAGE="true"
    - DISTRIB="conda" PYTHON_VERSION="3.4" INSTALL_ATLAS="true"
      NUMPY_VERSION="1.8" SCIPY_VERSION="0.14"
      COVERAGE="true"
install: source continuous_integration/install.sh

# command to run tests, e.g. python setup.py test
script:  python setup.py test