language: python

python:
  - "2.7_with_system_site_packages"
before_install:
  - sudo apt-get install -qq python-numpy python-scipy

install:
  - pip install cvxpy
  - python setup.py install

# command to run tests, e.g. python setup.py test
script:  py.test